### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [RIKEN-RCCS/EigenExa#2]
I suggest adding the topics `eigenvalue`, `linear-algebra`, `hpc` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by toshiyuki-imamura** [comment]
Thank you for your comment on adding the topics on categorization. I have added them.
